version: '2'
networks:
    ingress:
        external: true
services:

    nginx:
        build: .
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: unless-stopped
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/service-example.conf:/etc/nginx/service.conf
            # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=UTC
            - LETSENCRYPT=true
            - LE_EMAIL=admin@rissner.net
            - LE_FQDN=rissner.com,rissner.org,rissner.net,rissner.eu,www.rissner.com,www.rissner.org,www.rissner.eu,mail.rissner.com,mail.rissner.org,mail.rissner.net,mail.rissner.eu,pinky.rissner.net
            #- SSL_CERT=le-crt.pem
            #- SSL_KEY=le-key.pem
            #- SSL_CHAIN_CERT=le-chain-crt.pem
        networks:
            - default
            - ingress
